package Biblioteca;

import javafx.scene.layout.Pane;

public class ScrollablePane extends Pane{
    //PANO ONDE SÓ APARECE OS ELEMENTOS QUE DEVEM APARECER, USANDO UM ESQUEMA DE ILUSAO QUE NEM A GRADE MATEMATICA, DEIXANDO UMA MARGEM DE TAMANHO DE TELA
    //VER COMO LIGAR SCROLLABLE COM INTERACTIVE ETC....
    //A CAIXA PODERIA SER UM SCROLLABLE COM INTERACTIVE, TENDO UM ESQUEMA DE FADE NOS OBJETOS QUe CHEGAM E QUE VAO.
}
